// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var CatItem$ReactHooksTemplate = require("./CatItem.bs.js");

function App(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var catData = match[0];
  var catItems = catData !== undefined ? $$Array.map((function (cat) {
            return React.createElement(CatItem$ReactHooksTemplate.make, {
                        cat: cat,
                        key: cat[/* id */0]
                      });
          }), catData) : "Loading ...";
  return React.createElement("div", {
              className: "text-center"
            }, React.createElement("h1", undefined, "Cat Facts"), React.createElement("div", undefined, catItems));
}

var make = App;

exports.make = make;
/* react Not a pure module */
