// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function CatFactItem(Props) {
  var catFact = Props.catFact;
  return React.createElement("div", {
              className: "row"
            }, React.createElement("p", {
                  className: "col-1"
                }, String(catFact.upvotes), " ⬆️ upvote(s)"), React.createElement("p", {
                  className: "col-11 left"
                }, catFact.text));
}

var make = CatFactItem;

exports.make = make;
/* react Not a pure module */
