// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function CatItem(Props) {
  var cat = Props.cat;
  return React.createElement("div", undefined, React.createElement("h2", undefined, cat[/* text */1]), String(cat[/* upvotes */2]), " upvotes");
}

var make = CatItem;

exports.make = make;
/* react Not a pure module */
