// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var App$ReactHooksTemplate = require("./App.bs.js");

require('./index.css');
;

ReactDOMRe.renderToElementWithId(React.createElement(App$ReactHooksTemplate.make, {}), "root");

/*  Not a pure module */
